name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event.repository.default_branch == 'main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npx prisma generate

      - name: Run Prisma Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}

      - name: Build application
        run: npm run build

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ribpaycontainerregistry

      - name: Build and push container image to registry
        run: |
          echo "FROM node:18
          WORKDIR /app
          COPY package*.json ./
          RUN npm install
          COPY . .
          RUN npx prisma generate
          RUN npm run build
          EXPOSE 3000
          CMD [\"npm\", \"run\", \"start:prod\"]" > Dockerfile
          docker build --platform linux/amd64 -t ribpaycontainerregistry.azurecr.io/ribpay-nestjs-api:prodV0 .
          docker push ribpaycontainerregistry.azurecr.io/ribpay-nestjs-api:prodV0

      - name: Set ACR credentials in Azure Container App with retry
        run: |
          for i in {1..5}; do
            az containerapp registry set -n ribpay-prod-app -g api-ribpay-demo --server ribpaycontainerregistry.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }} && break || sleep 15;
          done

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: ribpaycontainerregistry.azurecr.io
          registryUsername: ${{ secrets.ACR_USERNAME }}
          registryPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppName: ribpay-prod-app
          resourceGroup: api-ribpay-demo
          imageToBuild: ribpaycontainerregistry.azurecr.io/ribpay-nestjs-api:prod
          buildArguments: |
            PRISMA_CLIENT=generate
