name: Update Environment

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    types: [synchronize]
    paths:
      - "src/**"
  push:
    branches:
      - main
    paths:
      - "src/**"

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  config:
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    name: Get Configuration
    uses: ./.github/workflows/environment_config.yml

  update_env:
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    name: Update ${{ needs.config.outputs.type }} Environment
    runs-on: ubuntu-latest

    needs: config
    environment: ${{ needs.config.outputs.type }}

    env:
      ENVIRONMENT_NAME: ${{ needs.config.outputs.name }}
      ENVIRONMENT_TYPE: ${{ needs.config.outputs.type }}
      UNIQUE_SUFFIX: ${{ github.event.number || github.ref_name }}
      DATABASE_NAME: ribpay_${{ github.event.number || github.ref_name || 'prod' }}_db

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd src
          npm install
          npx prisma generate

      - name: Build application
        run: |
          cd src
          npm run build

      - name: Run Prisma Migrations
        run: |
          cd src
          npx prisma migrate deploy
        env:
          DATABASE_URL: postgres://${{ secrets.POSTGRES_ADMIN_USERNAME }}:${{ secrets.POSTGRES_ADMIN_PASSWORD }}@${{ secrets.POSTGRES_SERVER_NAME }}.postgres.database.azure.com:5432/${{ env.DATABASE_NAME }}?sslmode=require

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ vars.ACR_NAME }} --username ${{ secrets.AZURE_ACR_USERNAME }} --password ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Update Azure CLI
        run: |
          az upgrade --yes

      - name: Install or Update Azure Container Apps extension
        run: |
          az extension add --name containerapp --upgrade

      - name: Set Image Tag
        id: image_tag
        run: echo "tag=${{ needs.config.outputs.type }}-${{ env.UNIQUE_SUFFIX }}-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build and push container image to registry
        run: |
          cd src
          echo "FROM node:18
          WORKDIR /app
          COPY package*.json ./
          RUN npm install
          COPY . .
          RUN npx prisma generate
          RUN npm run build
          EXPOSE 3000
          CMD [\"npm\", \"run\", \"start:prod\"]" > Dockerfile
          docker build --platform linux/amd64 -t ${{ vars.ACR_NAME }}.azurecr.io/ribpay-nestjs-api:${{ steps.image_tag.outputs.tag }} .
          docker push ${{ vars.ACR_NAME }}.azurecr.io/ribpay-nestjs-api:${{ steps.image_tag.outputs.tag }}

      - name: Transform type to lowercase
        id: lowercase_type
        uses: cloudposse/github-action-string-transformer@main
        with:
          operation: "lowercase"
          input-string: ${{ needs.config.outputs.type }}

      - name: Set Environment Variables
        run: |
          if [[ "${{ needs.config.outputs.type }}" == "Prod" ]]; then
            echo "DATABASE_URL=${{ secrets.DATABASE_URL_PROD }}" >> $GITHUB_ENV
          else
            echo "DATABASE_URL=postgres://${{ secrets.POSTGRES_ADMIN_USERNAME }}:${{ secrets.POSTGRES_ADMIN_PASSWORD }}@${{ secrets.POSTGRES_SERVER_NAME }}.postgres.database.azure.com:5432/${{ env.DATABASE_NAME }}?sslmode=require" >> $GITHUB_ENV
          fi
          echo "DEPLOYMENT_ID=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Set Secrets
        run: |
          if [[ "${{ needs.config.outputs.type }}" == "Prod" ]]; then
            az containerapp secret set \
              --name ${{ steps.lowercase_type.outputs.output-string }}-${{ env.UNIQUE_SUFFIX }} \
              --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
              --secrets \
                "inpi-username=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/inpi-username,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "inpi-password=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/inpi-password,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "oxlin-client-id=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/oxlin-client-id-prod,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "oxlin-client-secret=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/oxlin-client-secret-prod,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "lago-api-key=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/lago-api-key-prod,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "azure-storage=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/azure-storage-connection-string,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "aws-access-key-id=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/aws-access-key-id,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "aws-secret-access-key=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/aws-secret-access-key,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "payline-merchant-id=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/payline-merchant-id,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "payline-key-secret=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/payline-key-secret,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity"
          else
            az containerapp secret set \
              --name ${{ steps.lowercase_type.outputs.output-string }}-${{ env.UNIQUE_SUFFIX }} \
              --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
              --secrets \
                "inpi-username=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/inpi-username,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "inpi-password=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/inpi-password,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "oxlin-client-id=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/oxlin-client-id-dev,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "oxlin-client-secret=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/oxlin-client-secret-dev,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "lago-api-key=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/lago-api-key-dev,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "azure-storage=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/azure-storage-connection-string,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "aws-access-key-id=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/aws-access-key-id,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "aws-secret-access-key=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/aws-secret-access-key,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "payline-merchant-id=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/payline-merchant-id,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity" \
                "payline-key-secret=keyvaultref:https://ribpayapi-keyvault.vault.azure.net/secrets/payline-key-secret,identityref:/subscriptions/b81de495-68d7-476a-8de0-c5bd925431cf/resourcegroups/ribpay-api-deployment-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ribpay-managed-identity"
          fi

      - name: Update Container App with New Revision
        run: |
          az containerapp update \
            --name ${{ steps.lowercase_type.outputs.output-string }}-${{ env.UNIQUE_SUFFIX }} \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --cpu 0.5 \
            --memory 1.0Gi \
            --image ${{ vars.ACR_NAME }}.azurecr.io/ribpay-nestjs-api:${{ steps.image_tag.outputs.tag }} \
            --set-env-vars \
              "DATABASE_URL=${{ env.DATABASE_URL }}" \
              "DEPLOYMENT_ID=${{ env.DEPLOYMENT_ID }}" \
              "INPI_USERNAME=secretref:inpi-username" \
              "INPI_PASSWORD=secretref:inpi-password" \
              "OXLIN_CLIENT_ID=secretref:oxlin-client-id" \
              "OXLIN_CLIENT_SECRET=secretref:oxlin-client-secret" \
              "LAGO_API_KEY=secretref:lago-api-key" \
              "AZURE_STORAGE_CONNECTION_STRING=secretref:azure-storage" \
              "AWS_ACCESS_KEY_ID=secretref:aws-access-key-id" \
              "AWS_SECRET_ACCESS_KEY=secretref:aws-secret-access-key" \
              "PAYLINE_MERCHANT_ID=secretref:payline-merchant-id" \
              "PAYLINE_KEY_SECRET=secretref:payline-key-secret"

      - name: Output deployment information
        run: |
          echo "- [View the deployed API](https://${{ steps.lowercase_type.outputs.output-string }}-${{ env.UNIQUE_SUFFIX }}.azurecontainerapps.io)" >> $GITHUB_STEP_SUMMARY
