name: Create Environment

permissions:
  id-token: write
  contents: read

on:
  create:
  pull_request:
    types: [opened, reopened]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  config:
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    name: Get Configuration
    uses: ./.github/workflows/environment_config.yml

  create_env:
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    name: Create ${{ needs.config.outputs.type }} Environment
    runs-on: ubuntu-latest

    needs: config
    environment: ${{ needs.config.outputs.type }}

    env:
      ENVIRONMENT_NAME: ${{ needs.config.outputs.name }}
      ENVIRONMENT_TYPE: ${{ needs.config.outputs.type }}
      UNIQUE_SUFFIX: ${{ github.event.number || github.ref_name }}
      DATABASE_NAME: ribpay_${{ github.event.number || github.ref_name || 'prod' }}_db

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd src
          npm install
          npx prisma generate
          
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # - name: Create PostgreSQL Database
      #   run: |
      #     az postgres db create --name ${{ env.DATABASE_NAME }} --server-name ${{ secrets.POSTGRES_SERVER_NAME }} --resource-group api-ribpay-demo
      #   env:
      #     POSTGRES_ADMIN_USER: ${{ secrets.POSTGRES_ADMIN_USER }}
      #     POSTGRES_ADMIN_PASSWORD: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}
      #     POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}

      # - name: Set DATABASE_URL
      #   run: |
      #     echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_ADMIN_USER }}:${{ secrets.POSTGRES_ADMIN_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:5432/${{ env.DATABASE_NAME }}" >> $GITHUB_ENV

      - name: Build application
        run: |
          cd src
          npm run build

      - name: Run Prisma Migrations
        run: |
          cd src
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}


      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ vars.ACR_NAME }} --username ${{ secrets.AZURE_ACR_USERNAME }} --password ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push container image to registry
        run: |
          cd src
          echo "FROM node:18
          WORKDIR /app
          COPY package*.json ./
          RUN npm install
          COPY . .
          RUN npx prisma generate
          RUN npm run build
          EXPOSE 3000
          CMD [\"npm\", \"run\", \"start:prod\"]" > Dockerfile
          docker build --platform linux/amd64 -t ${{ vars.ACR_NAME }}.azurecr.io/ribpay-nestjs-api:${{ needs.config.outputs.type }}-${{ env.UNIQUE_SUFFIX }} .
          docker push ${{ vars.ACR_NAME }}.azurecr.io/ribpay-nestjs-api:${{ needs.config.outputs.type }}-${{ env.UNIQUE_SUFFIX }}

      - name: Transform type to lowercase
        id: lowercase_type
        uses: cloudposse/github-action-string-transformer@main
        with:
          operation: "lowercase"
          input-string: ${{ needs.config.outputs.type }}

      - name: Create Container App Environment
        run: |
          az containerapp env create \
            --name ${{ needs.config.outputs.type }}-env-${{ env.UNIQUE_SUFFIX }} \
            --resource-group ${{ vars.AZURE_RESSOURCE_GROUP}} \
            --location westeurope

      - name: Deploy Container App
        run: |
          az containerapp create \
            --name ${{ steps.lowercase_type.outputs.output-string }}-${{ env.UNIQUE_SUFFIX }} \
            --resource-group ${{ vars.AZURE_RESSOURCE_GROUP }} \
            --environment ${{ needs.config.outputs.type }}-env-${{ env.UNIQUE_SUFFIX }} \
            --image ${{ vars.ACR_NAME }}.azurecr.io/ribpay-nestjs-api:${{ needs.config.outputs.type }}-${{ env.UNIQUE_SUFFIX }} \
            --target-port 3000 \
            --ingress 'external' \
            --registry-server ${{ vars.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.AZURE_ACR_USERNAME }} \
            --registry-password ${{ secrets.AZURE_ACR_PASSWORD }} \
            --env-vars "DATABASE_URL=${{ secrets.DATABASE_URL_PROD }}" \
                       "INPI_USERNAME=${{ secrets.INPI_USERNAME }}" \
                        "INPI_PASSWORD=${{ secrets.INPI_PASSWORD }}" \
                        "OXLIN_CLIENT_ID=${{ secrets.OXLIN_CLIENT_ID }}" \
                        "OXLIN_CLIENT_SECRET=${{ secrets.OXLIN_CLIENT_SECRET }}" \
                        "LAGO_API_KEY=${{ secrets.LAGO_API_KEY }}" \
                        "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"

      - name: Output deployment information
        run: |
          echo "- [View the deployed API](https://${{ env.ENVIRONMENT_NAME }}.azurecontainerapps.io)" >> $GITHUB_STEP_SUMMARY
