name: Delete Environment

permissions:
  id-token: write

on:
  delete:
  pull_request:
    types: [closed]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  config:
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    name: Get Configuration
    uses: ./.github/workflows/environment_config.yml

  delete_env:
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    name: Delete ${{ needs.config.outputs.type }} Environment
    runs-on: ubuntu-latest

    needs: config
    environment: ${{ needs.config.outputs.type }}

    env:
      ENVIRONMENT_NAME: ${{ needs.config.outputs.name }}
      ENVIRONMENT_TYPE: ${{ needs.config.outputs.type }}
      UNIQUE_SUFFIX: ${{ github.event.number || github.ref_name }}

    steps:
      - name: Install DevCenter CLI Extension
        run: az extension add --name devcenter --upgrade

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Transform type to lowercase
        id: lowercase_type
        uses: cloudposse/github-action-string-transformer@main
        with:
          operation: "lowercase"
          input-string: ${{ needs.config.outputs.type }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ vars.ACR_NAME }} --username ${{ secrets.AZURE_ACR_USERNAME }} --password ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Delete Image Tag from ACR
        run: |
          az acr repository delete --name ${{ vars.ACR_NAME }} --image ribpay-nestjs-api:${{ needs.config.outputs.type }}-${{ env.UNIQUE_SUFFIX }} --yes

      # - name: Delete PostgreSQL Database
      #   run: |
      #     az postgres db delete --name ${{ env.DATABASE_NAME }} --server-name ${{ secrets.POSTGRES_SERVER_NAME }} --resource-group ribpay-api-demo --yes
      #   env:
      #     POSTGRES_ADMIN_USER: ${{ secrets.POSTGRES_ADMIN_USER }}
      #     POSTGRES_ADMIN_PASSWORD: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}
      #     POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      #     DATABASE_NAME: ribpay_${{ github.event.number || github.ref_name || 'prod' }}_db

      - name: Delete Container App
        run: |
          az containerapp delete --name ${{ steps.lowercase_type.outputs.output-string }}-${{ env.UNIQUE_SUFFIX }} --resource-group ribpay-api-deployment-demo --yes
