name: Trigger auto deployment for ribpay-container-app

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/ribpay-container-app-AutoDeployTrigger-5f1d9b64-e076-47ae-bf3a-269894c2b05f.yml'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write # This is required for requesting the OIDC JWT Token
      contents: read # Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npx prisma generate

      - name: Build application
        run: |
          npm run build

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RIBPAYCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RIBPAYCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RIBPAYCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ribpayregistry.azurecr.io
          registryUsername: ${{ secrets.RIBPAYCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RIBPAYCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: ribpay-container-app
          resourceGroup: ribpayTestApiDeployResourceGroup
          imageToBuild: ribpayregistry.azurecr.io/ribpay-container-app:${{ github.sha }}
          buildArguments: |
            PRISMA_CLIENT=generate
